---
- include_tasks: apt-stuff.yml
- include_tasks: go-tools.yml
- include_tasks: github-repos.yml
- include_tasks: python-tools.yml
- include_tasks: gem-tools.yml
- include_tasks: resolution-script.yml
- include_tasks: cargo-tools.yml
